org.gradle.caching=true
org.gradle.parallel=true
frameworkVersion=0.4.0
springBootVersion=4.1.0
graalvmNativeBuildToolsVersion=1.1.1
springDependencyManagementVersion=1.1.7
spotlessVersion=8.8.0
googleJavaFormatVersion=1.35.0
junitVersion=6.0.3
jspecifyVersion=1.0.0
japicmpVersion=0.26.1
binaryCompatibilityBaselineVersion=0.3.0
cycloneDxVersion=3.3.0
sonarQubePluginVersion=7.2.3.7755
jacocoVersion=0.8.15
minimumLineCoverage=0.50
