plugins {
    id 'java'
    id 'org.springframework.boot'
    id 'org.graalvm.buildtools.native'
    id 'io.spring.dependency-management'
}

group = 'com.smbtech.examples'
version = '0.4.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

def frameworkRoot = file('../..')
apply from: '../security-dependency-overrides.gradle'

repositories {
    maven {
        name = 'platformBuild'
        url = uri("${frameworkRoot}/spring-boot-service-framework-platform/build/repository")
    }
    maven {
        name = 'errorHandlingStarterBuild'
        url = uri("${frameworkRoot}/spring-boot-service-framework-starters/spring-boot-service-framework-starter-error-handling/build/repository")
    }
    maven {
        name = 'errorCoreBuild'
        url = uri("${frameworkRoot}/spring-boot-service-framework-error-core/build/repository")
    }
    maven {
        name = 'httpClientCoreBuild'
        url = uri("${frameworkRoot}/spring-boot-service-framework-http-client-core/build/repository")
    }
    maven {
        name = 'commonsBuild'
        url = uri("${frameworkRoot}/spring-boot-service-framework-commons/build/repository")
    }
    maven {
        name = 'loggingCoreBuild'
        url = uri("${frameworkRoot}/spring-boot-service-framework-logging-core/build/repository")
    }
    mavenCentral()
}

dependencies {
    implementation platform('com.smbtech:spring-boot-service-framework-platform:0.4.0')

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'com.smbtech:spring-boot-service-framework-starter-error-handling'
    implementation 'com.smbtech:spring-boot-service-framework-http-client-core'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.security:spring-security-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

configurations.configureEach {
    resolutionStrategy.cacheChangingModulesFor 0, 'seconds'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.compilerArgs += ['-parameters']
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}
