plugins {
    id 'java'
    id 'org.springframework.boot'
    id 'io.spring.dependency-management'
}

group = 'com.smbtech.examples'
version = '0.3.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

def frameworkRoot = file('../..')

repositories {
    maven {
        name = 'starterBuild'
        url = uri("${frameworkRoot}/spring-boot-service-framework-starters/spring-boot-service-framework-starter-logging/build/repository")
    }
    maven {
        name = 'commonsBuild'
        url = uri("${frameworkRoot}/spring-boot-service-framework-commons/build/repository")
    }
    maven {
        name = 'coreBuild'
        url = uri("${frameworkRoot}/spring-boot-service-framework-logging-core/build/repository")
    }
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-micrometer-tracing-brave'
    implementation 'io.micrometer:micrometer-tracing-bridge-brave'
    implementation 'org.springframework.boot:spring-boot-starter-jackson'
    implementation 'com.smbtech:spring-boot-service-framework-starter-logging:0.3.0'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

configurations.configureEach {
    resolutionStrategy.cacheChangingModulesFor 0, 'seconds'
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}
