plugins {
    id 'com.smbtech.service-framework.spring-boot-starter'
}

description = 'Mock services starter for Spring Boot services'

dependencies {
    api project(':spring-boot-service-framework-mock-core')

    implementation 'org.springframework.boot:spring-boot-autoconfigure'
    implementation 'org.springframework:spring-core'
    implementation 'org.springframework:spring-web'
    implementation 'org.springframework:spring-webmvc'
    api 'tools.jackson.core:jackson-databind'
    implementation 'tools.jackson.dataformat:jackson-dataformat-yaml'

    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc'
}

publishing {
    publications {
        named('mavenJava', MavenPublication) {
            pom {
                name = 'Spring Boot Service Framework - Mock Starter'
            }
        }
    }
}
