plugins {
    id 'com.smbtech.service-framework.spring-boot-starter'
}

description = 'Configured RestClient starter for Spring Boot services'

dependencies {
    api project(':spring-boot-service-framework-http-client-core')
    api 'org.springframework.boot:spring-boot-starter-restclient'
    api 'org.springframework.boot:spring-boot-starter-oauth2-client'

    implementation project(':spring-boot-service-framework-logging-core')
    implementation 'org.springframework.boot:spring-boot-autoconfigure'
    implementation 'org.apache.httpcomponents.client5:httpclient5'
    implementation 'com.fasterxml.jackson.core:jackson-databind'
    implementation 'io.micrometer:micrometer-core'
    implementation 'org.slf4j:slf4j-api'
    testImplementation 'org.springframework.boot:spring-boot-starter-restclient-test'
}

publishing {
    publications {
        named('mavenJava', MavenPublication) {
            pom {
                name = 'Spring Boot Service Framework - REST Client Starter'
            }
        }
    }
}
