plugins {
    id 'java'
    id 'org.springframework.boot'
    id 'org.graalvm.buildtools.native'
    id 'io.spring.dependency-management'
}

group = 'com.smbtech.examples'
version = '0.5.1'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

def frameworkRoot = file('../..')
apply from: '../security-dependency-overrides.gradle'

repositories {
    maven {
        name = 'platformBuild'
        url = uri("${frameworkRoot}/spring-boot-service-framework-platform/build/repository")
    }
    maven {
        name = 'restClientStarterBuild'
        url = uri("${frameworkRoot}/spring-boot-service-framework-starters/spring-boot-service-framework-starter-rest-client/build/repository")
    }
    maven {
        name = 'loggingStarterBuild'
        url = uri("${frameworkRoot}/spring-boot-service-framework-starters/spring-boot-service-framework-starter-logging/build/repository")
    }
    maven {
        name = 'httpClientCoreBuild'
        url = uri("${frameworkRoot}/spring-boot-service-framework-http-client-core/build/repository")
    }
    maven {
        name = 'commonsBuild'
        url = uri("${frameworkRoot}/spring-boot-service-framework-commons/build/repository")
    }
    maven {
        name = 'loggingCoreBuild'
        url = uri("${frameworkRoot}/spring-boot-service-framework-logging-core/build/repository")
    }
    mavenCentral()
}

dependencies {
    implementation platform('com.smbtech:spring-boot-service-framework-platform:0.5.1')

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-micrometer-tracing-brave'
    implementation 'io.micrometer:micrometer-tracing-bridge-brave'
    implementation 'com.smbtech:spring-boot-service-framework-starter-rest-client'
    implementation 'com.smbtech:spring-boot-service-framework-starter-logging'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

configurations.configureEach {
    resolutionStrategy.cacheChangingModulesFor 0, 'seconds'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.compilerArgs += ['-parameters']
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}
